# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.remote_server_api import RemoteServerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRemoteServerApi(unittest.TestCase):
    """RemoteServerApi unit test stubs"""

    def setUp(self):
        self.api = RemoteServerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_process_list(self):
        """Test case for get_process_list

        """
        pass

    def test_screenshot(self):
        """Test case for screenshot

        """
        pass

    def test_system_reboot(self):
        """Test case for system_reboot

        """
        pass

    def test_system_shut_down(self):
        """Test case for system_shut_down

        """
        pass


if __name__ == '__main__':
    unittest.main()
